// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optera.Configuration;

#nullable disable

namespace Optera.Configuration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Optera.Configuration.Models.DataTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ItemsPerPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DataTables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ItemsPerPage = 10,
                            Name = "countries-list",
                            Title = "Countries"
                        });
                });

            modelBuilder.Entity("Optera.Configuration.Models.DataTableColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Color")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("DataTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Datatype")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("DisplayCurrency")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCheck")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("Sortable")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DataTableId");

                    b.ToTable("DataTableColumns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name",
                            Order = 1,
                            Sortable = true,
                            Text = "Country Name",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name_OtherLanguage",
                            Order = 2,
                            Sortable = true,
                            Text = "Country Name (Other)",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "isoCode",
                            Order = 3,
                            Sortable = true,
                            Text = "ISO Code",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "creator",
                            Order = 4,
                            Sortable = true,
                            Text = "Created By",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "updater",
                            Order = 5,
                            Sortable = true,
                            Text = "Modified By",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "createdAt",
                            Order = 6,
                            Sortable = true,
                            Text = "Created At",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "updatedAt",
                            Order = 7,
                            Sortable = true,
                            Text = "Modified At",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            DataTableId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "status",
                            Order = 8,
                            Sortable = true,
                            Text = "Status",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Optera.Configuration.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Data")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool?>("Expanded")
                        .HasColumnType("bit");

                    b.Property<bool?>("Group")
                        .HasColumnType("bit");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("bit");

                    b.Property<bool?>("Home")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Link")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Target")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Home = true,
                            Icon = "eva home-outline",
                            Link = "/pages/dashboard",
                            Order = 0,
                            Title = "Home"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Data = "AUTH_1000",
                            Icon = "eva options-2-outline",
                            Order = 0,
                            Title = "Miscellaneous"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Data = "AUTH_1010",
                            Icon = "eva globe-outline",
                            Link = "/pages/miscellaneous/countries",
                            Order = 10,
                            ParentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Title = "Countries"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Data = "AUTH_1020",
                            Icon = "eva home-outline",
                            Link = "/pages/miscellaneous/cities",
                            Order = 20,
                            ParentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Title = "Cities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Data = "AUTH_1030",
                            Icon = "eva map-outline",
                            Link = "/pages/miscellaneous/regions",
                            Order = 30,
                            ParentId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Title = "Regions"
                        });
                });

            modelBuilder.Entity("Optera.Configuration.Models.DataTableColumn", b =>
                {
                    b.HasOne("Optera.Configuration.Models.DataTable", "DataTable")
                        .WithMany("DataTableColumns")
                        .HasForeignKey("DataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTable");
                });

            modelBuilder.Entity("Optera.Configuration.Models.MenuItem", b =>
                {
                    b.HasOne("Optera.Configuration.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Optera.Configuration.Models.DataTable", b =>
                {
                    b.Navigation("DataTableColumns");
                });

            modelBuilder.Entity("Optera.Configuration.Models.MenuItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
