// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optera.DataAccess;

#nullable disable

namespace Optera.DataAccess.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250818133630_AddUserAuthorizationToAuthorization")]
    partial class AddUserAuthorizationToAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Optera.Models.Authorization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Authorizations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AUTH_1000",
                            Name = "Settings",
                            Order = 0
                        },
                        new
                        {
                            Id = 2L,
                            Code = "AUTH_1010",
                            Name = "Countries",
                            Order = 10,
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Code = "AUTH_1020",
                            Name = "Cities",
                            Order = 20,
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Code = "AUTH_1030",
                            Name = "Regions",
                            Order = 30,
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Code = "AUTH_1040",
                            Name = "Categories",
                            Order = 40,
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Code = "AUTH_1041",
                            Name = "Categories Items",
                            Order = 41,
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 7L,
                            Code = "AUTH_2000",
                            Name = "Business Process",
                            Order = 0
                        },
                        new
                        {
                            Id = 8L,
                            Code = "AUTH_2010",
                            Name = "Quotation Request",
                            Order = 10,
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 9L,
                            Code = "AUTH_2011",
                            Name = "Add Quotation Request",
                            Order = 11,
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 10L,
                            Code = "AUTH_2012",
                            Name = "Edit Quotation Request",
                            Order = 12,
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 11L,
                            Code = "AUTH_3000",
                            Name = "Administration",
                            Order = 0
                        },
                        new
                        {
                            Id = 12L,
                            Code = "AUTH_3010",
                            Name = "Groups",
                            Order = 10,
                            ParentId = 11L
                        },
                        new
                        {
                            Id = 13L,
                            Code = "AUTH_3011",
                            Name = "Add Group",
                            Order = 11,
                            ParentId = 12L
                        },
                        new
                        {
                            Id = 14L,
                            Code = "AUTH_3020",
                            Name = "Users",
                            Order = 20,
                            ParentId = 11L
                        },
                        new
                        {
                            Id = 15L,
                            Code = "AUTH_3021",
                            Name = "Add User",
                            Order = 21,
                            ParentId = 14L
                        });
                });

            modelBuilder.Entity("Optera.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            Description = "Customer Business Sector",
                            Name = "Sector",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            Description = "Nationalities",
                            Name = "Nationalities",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            Description = "Positions",
                            Name = "Positions",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            Description = "Customer Class",
                            Name = "Classes",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            Description = "Customer Identification Types",
                            Name = "Identification Types",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        });
                });

            modelBuilder.Entity("Optera.Models.CategoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryItems");
                });

            modelBuilder.Entity("Optera.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            Name = "Manama",
                            Name_OtherLanguage = "المنامة",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        });
                });

            modelBuilder.Entity("Optera.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISOCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            ISOCode = "BHR",
                            Name = "Bahrain",
                            Name_OtherLanguage = "البحرين",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        });
                });

            modelBuilder.Entity("Optera.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecondaryNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClassId");

                    b.HasIndex("CountryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Optera.Models.CustomerContactPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PositionId");

                    b.ToTable("CustomerContactPersons");
                });

            modelBuilder.Entity("Optera.Models.CustomerIdentification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdentificationTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdentificationTypeId");

                    b.ToTable("CustomerIdentifications");
                });

            modelBuilder.Entity("Optera.Models.DataTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ItemsPerPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataTables");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ItemsPerPage = 10,
                            Name = "countries-list",
                            Title = "Countries"
                        },
                        new
                        {
                            Id = 2L,
                            ItemsPerPage = 10,
                            Name = "cities-list",
                            Title = "Cities"
                        },
                        new
                        {
                            Id = 3L,
                            ItemsPerPage = 10,
                            Name = "regions-list",
                            Title = "Regions"
                        },
                        new
                        {
                            Id = 4L,
                            ItemsPerPage = 10,
                            Name = "categories-list",
                            Title = "Categories"
                        },
                        new
                        {
                            Id = 5L,
                            ItemsPerPage = 10,
                            Name = "categories-items-list",
                            Title = "Category Items"
                        },
                        new
                        {
                            Id = 6L,
                            ItemsPerPage = 10,
                            Name = "quotations-list",
                            Title = "Quotations"
                        },
                        new
                        {
                            Id = 7L,
                            ItemsPerPage = 10,
                            Name = "groups-list",
                            Title = "Groups"
                        },
                        new
                        {
                            Id = 8L,
                            ItemsPerPage = 10,
                            Name = "users-list",
                            Title = "Users"
                        });
                });

            modelBuilder.Entity("Optera.Models.DataTableColumn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DataTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("Datatype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisplayCurrency")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCheck")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("Sortable")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DataTableId");

                    b.ToTable("DataTableColumns");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataTableId = 1L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 2L,
                            DataTableId = 1L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name",
                            Order = 1,
                            Sortable = true,
                            Text = "Country Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 3L,
                            DataTableId = 1L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name_OtherLanguage",
                            Order = 2,
                            Sortable = true,
                            Text = "Country Name (Other Lang.)",
                            Visible = true
                        },
                        new
                        {
                            Id = 4L,
                            DataTableId = 1L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "status",
                            Order = 3,
                            Sortable = true,
                            Text = "Status",
                            Visible = true
                        },
                        new
                        {
                            Id = 5L,
                            DataTableId = 2L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 6L,
                            DataTableId = 2L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name",
                            Order = 1,
                            Sortable = true,
                            Text = "City Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 7L,
                            DataTableId = 2L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name_OtherLanguage",
                            Order = 2,
                            Sortable = true,
                            Text = "City Name (Other Lang.)",
                            Visible = true
                        },
                        new
                        {
                            Id = 8L,
                            DataTableId = 2L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "countryName",
                            Order = 3,
                            Sortable = true,
                            Text = "Country",
                            Visible = true
                        },
                        new
                        {
                            Id = 9L,
                            DataTableId = 2L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "status",
                            Order = 4,
                            Sortable = true,
                            Text = "Status",
                            Visible = true
                        },
                        new
                        {
                            Id = 10L,
                            DataTableId = 3L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 11L,
                            DataTableId = 3L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name",
                            Order = 1,
                            Sortable = true,
                            Text = "Region Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 12L,
                            DataTableId = 3L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name_OtherLanguage",
                            Order = 2,
                            Sortable = true,
                            Text = "Region Name (Other Lang.)",
                            Visible = true
                        },
                        new
                        {
                            Id = 13L,
                            DataTableId = 3L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "cityName",
                            Order = 3,
                            Sortable = true,
                            Text = "City",
                            Visible = true
                        },
                        new
                        {
                            Id = 14L,
                            DataTableId = 3L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "cityId",
                            Order = 4,
                            Sortable = true,
                            Text = "City ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 15L,
                            DataTableId = 3L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "countryName",
                            Order = 5,
                            Sortable = true,
                            Text = "Country",
                            Visible = true
                        },
                        new
                        {
                            Id = 16L,
                            DataTableId = 3L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "status",
                            Order = 6,
                            Sortable = true,
                            Text = "Status",
                            Visible = true
                        },
                        new
                        {
                            Id = 17L,
                            DataTableId = 4L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 18L,
                            DataTableId = 4L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name",
                            Order = 1,
                            Sortable = true,
                            Text = "Category Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 19L,
                            DataTableId = 4L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "description",
                            Order = 2,
                            Sortable = true,
                            Text = "Description",
                            Visible = true
                        },
                        new
                        {
                            Id = 20L,
                            DataTableId = 4L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "status",
                            Order = 3,
                            Sortable = true,
                            Text = "Status",
                            Visible = true
                        },
                        new
                        {
                            Id = 21L,
                            DataTableId = 5L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 22L,
                            DataTableId = 5L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name",
                            Order = 1,
                            Sortable = true,
                            Text = "Category Item Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 23L,
                            DataTableId = 5L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name_OtherLanguage",
                            Order = 2,
                            Sortable = true,
                            Text = "Category Item Name (Other Lang.)",
                            Visible = true
                        },
                        new
                        {
                            Id = 24L,
                            DataTableId = 5L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "categoryName",
                            Order = 3,
                            Sortable = true,
                            Text = "Category Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 25L,
                            DataTableId = 5L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "categoryId",
                            Order = 4,
                            Sortable = true,
                            Text = "Category ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 26L,
                            DataTableId = 5L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "status",
                            Order = 5,
                            Sortable = true,
                            Text = "Status",
                            Visible = true
                        },
                        new
                        {
                            Id = 27L,
                            DataTableId = 6L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 28L,
                            DataTableId = 6L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "code",
                            Order = 1,
                            Sortable = true,
                            Text = "Code",
                            Visible = true
                        },
                        new
                        {
                            Id = 29L,
                            DataTableId = 6L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "customerName",
                            Order = 2,
                            Sortable = true,
                            Text = "Customer Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 30L,
                            DataTableId = 6L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "customerBrandName",
                            Order = 3,
                            Sortable = true,
                            Text = "Brand Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 31L,
                            DataTableId = 6L,
                            Datatype = "date",
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "effectiveDate",
                            Order = 4,
                            Sortable = true,
                            Text = "Effective Date",
                            Visible = true
                        },
                        new
                        {
                            Id = 32L,
                            DataTableId = 6L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "status",
                            Order = 5,
                            Sortable = true,
                            Text = "Status",
                            Visible = true
                        },
                        new
                        {
                            Id = 33L,
                            DataTableId = 7L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 34L,
                            DataTableId = 7L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "name",
                            Order = 1,
                            Sortable = true,
                            Text = "Group Name",
                            Visible = true
                        },
                        new
                        {
                            Id = 35L,
                            DataTableId = 7L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "normalizedName",
                            Order = 2,
                            Sortable = true,
                            Text = "Group Name (Normalized)",
                            Visible = true
                        },
                        new
                        {
                            Id = 36L,
                            DataTableId = 8L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "id",
                            Order = 0,
                            Sortable = true,
                            Text = "ID",
                            Visible = false
                        },
                        new
                        {
                            Id = 37L,
                            DataTableId = 8L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "userName",
                            Order = 1,
                            Sortable = true,
                            Text = "Username",
                            Visible = true
                        },
                        new
                        {
                            Id = 38L,
                            DataTableId = 8L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "normalizedUserName",
                            Order = 2,
                            Sortable = true,
                            Text = "Normalized Username",
                            Visible = true
                        },
                        new
                        {
                            Id = 39L,
                            DataTableId = 8L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "email",
                            Order = 3,
                            Sortable = true,
                            Text = "Email",
                            Visible = true
                        },
                        new
                        {
                            Id = 40L,
                            DataTableId = 8L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "normalizedEmail",
                            Order = 4,
                            Sortable = true,
                            Text = "Normalized Email",
                            Visible = true
                        },
                        new
                        {
                            Id = 41L,
                            DataTableId = 8L,
                            DisplayCurrency = false,
                            IsCheck = false,
                            Name = "emailConfirmed",
                            Order = 5,
                            Sortable = true,
                            Text = "Email Confirmed",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Optera.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NationalityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Optera.Models.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Expanded")
                        .HasColumnType("bit");

                    b.Property<bool?>("Group")
                        .HasColumnType("bit");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("bit");

                    b.Property<bool?>("Home")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Home = true,
                            Icon = "home-outline",
                            Link = "/pages/dashboard",
                            Order = 0,
                            Title = "Home"
                        },
                        new
                        {
                            Id = 2L,
                            Data = "AUTH_1000",
                            Icon = "settings-outline",
                            Order = 0,
                            Title = "Settings"
                        },
                        new
                        {
                            Id = 3L,
                            Data = "AUTH_1010",
                            Icon = "arrow-right",
                            Link = "settings/countries",
                            Order = 10,
                            ParentId = 2L,
                            Title = "Countries"
                        },
                        new
                        {
                            Id = 4L,
                            Data = "AUTH_1020",
                            Icon = "arrow-right",
                            Link = "settings/cities",
                            Order = 20,
                            ParentId = 2L,
                            Title = "Cities"
                        },
                        new
                        {
                            Id = 5L,
                            Data = "AUTH_1030",
                            Icon = "arrow-right",
                            Link = "settings/regions",
                            Order = 30,
                            ParentId = 2L,
                            Title = "Regions"
                        },
                        new
                        {
                            Id = 6L,
                            Data = "AUTH_1040",
                            Icon = "arrow-right",
                            Link = "settings/categories",
                            Order = 40,
                            ParentId = 2L,
                            Title = "Categories"
                        },
                        new
                        {
                            Id = 7L,
                            Data = "AUTH_2000",
                            Icon = "flip-2-outline",
                            Order = 0,
                            Title = "Business Process"
                        },
                        new
                        {
                            Id = 8L,
                            Data = "AUTH_2010",
                            Icon = "arrow-right",
                            Link = "business-process/quotations",
                            Order = 10,
                            ParentId = 7L,
                            Title = "Quotation Request"
                        },
                        new
                        {
                            Id = 9L,
                            Data = "AUTH_2020",
                            Icon = "arrow-right",
                            Link = "business-process/contracts",
                            Order = 20,
                            ParentId = 7L,
                            Title = "Contract Request"
                        },
                        new
                        {
                            Id = 10L,
                            Data = "AUTH_3000",
                            Icon = "shield-outline",
                            Order = 0,
                            Title = "Administration"
                        },
                        new
                        {
                            Id = 11L,
                            Data = "AUTH_3010",
                            Icon = "arrow-right",
                            Link = "admin/groups",
                            Order = 10,
                            ParentId = 10L,
                            Title = "Groups"
                        },
                        new
                        {
                            Id = 12L,
                            Data = "AUTH_3020",
                            Icon = "arrow-right",
                            Link = "admin/users",
                            Order = 20,
                            ParentId = 10L,
                            Title = "Users"
                        });
                });

            modelBuilder.Entity("Optera.Models.Quotation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("InChargePersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InChargePersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InChargePersonPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InChargePersonPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InChargePersonPositionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfBranches")
                        .HasColumnType("int");

                    b.Property<long?>("PaymentTermId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PermissionRequired")
                        .HasColumnType("bit");

                    b.Property<long?>("PriceNoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ValidityPeriodId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InChargePersonPositionId");

                    b.HasIndex("PaymentTermId");

                    b.HasIndex("PriceNoteId");

                    b.HasIndex("ValidityPeriodId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("Optera.Models.ReferenceNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("LastSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment1_Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment2_Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment3_Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment4_Format")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LastSequence = 0L,
                            Prefix = "CUS",
                            Segment1 = "000000",
                            Segment1_Format = "Sequence"
                        },
                        new
                        {
                            Id = 2L,
                            LastSequence = 0L,
                            Prefix = "QUT",
                            Segment1 = "00",
                            Segment2 = "yyMMdd",
                            Segment2_Format = "Date",
                            Segment3 = "000000",
                            Segment3_Format = "Sequence"
                        });
                });

            modelBuilder.Entity("Optera.Models.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_OtherLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Optera.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Optera.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Optera.Models.Workflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfLevels")
                        .HasColumnType("int");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workflow");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Creator = "System",
                            Description = "Quotation Approval Cycle",
                            NumberOfLevels = 3,
                            Process = "Quotation",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Updator = "System"
                        });
                });

            modelBuilder.Entity("Optera.Models.WorkflowScenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("Updator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowScenarios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActorId = 3,
                            ApprovalStatus = "ApprovedBySalesCoordinator",
                            Creator = "System",
                            Name = "Quotation - Sales Coordinator Scenario",
                            PreviousStatus = "UnderReview",
                            RejectionStatus = "Submitted",
                            Status = "Active",
                            StepOrder = 1,
                            Updator = "System",
                            WorkflowId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ActorId = 4,
                            ApprovalStatus = "ApprovedBySalesExecutive",
                            Creator = "System",
                            Name = "Quotation - Sales Executive Scenario",
                            PreviousStatus = "ApprovedBySalesCoordinator",
                            RejectionStatus = "Submitted",
                            Status = "Active",
                            StepOrder = 2,
                            Updator = "System",
                            WorkflowId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ActorId = 2,
                            ApprovalStatus = "ApprovedByCEO",
                            Creator = "System",
                            Name = "Quotation - CEO Scenario",
                            PreviousStatus = "ApprovedBySalesExecutive",
                            RejectionStatus = "Submitted",
                            Status = "Active",
                            StepOrder = 3,
                            Updator = "System",
                            WorkflowId = 1L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Optera.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Optera.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Optera.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Optera.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optera.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Optera.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Optera.Models.Authorization", b =>
                {
                    b.HasOne("Optera.Models.Authorization", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Optera.Models.CategoryItem", b =>
                {
                    b.HasOne("Optera.Models.Category", "Category")
                        .WithMany("CategoryItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Optera.Models.City", b =>
                {
                    b.HasOne("Optera.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Optera.Models.Customer", b =>
                {
                    b.HasOne("Optera.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Optera.Models.CategoryItem", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optera.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Optera.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Class");

                    b.Navigation("Country");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Optera.Models.CustomerContactPerson", b =>
                {
                    b.HasOne("Optera.Models.Customer", "Customer")
                        .WithMany("CustomerContactPersons")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optera.Models.CategoryItem", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Optera.Models.CustomerIdentification", b =>
                {
                    b.HasOne("Optera.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Optera.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Optera.Models.Customer", "Customer")
                        .WithMany("CustomerIdentifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optera.Models.CategoryItem", "IdentificationType")
                        .WithMany()
                        .HasForeignKey("IdentificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Customer");

                    b.Navigation("IdentificationType");
                });

            modelBuilder.Entity("Optera.Models.DataTableColumn", b =>
                {
                    b.HasOne("Optera.Models.DataTable", "DataTable")
                        .WithMany("DataTableColumns")
                        .HasForeignKey("DataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTable");
                });

            modelBuilder.Entity("Optera.Models.Employee", b =>
                {
                    b.HasOne("Optera.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Optera.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Optera.Models.CategoryItem", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Optera.Models.CategoryItem", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Optera.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Optera.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Nationality");

                    b.Navigation("Position");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Optera.Models.MenuItem", b =>
                {
                    b.HasOne("Optera.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Optera.Models.Quotation", b =>
                {
                    b.HasOne("Optera.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optera.Models.Employee", "Employee")
                        .WithMany("Quotations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Optera.Models.CategoryItem", "InChargePersonPosition")
                        .WithMany()
                        .HasForeignKey("InChargePersonPositionId");

                    b.HasOne("Optera.Models.CategoryItem", "PaymentTerm")
                        .WithMany()
                        .HasForeignKey("PaymentTermId");

                    b.HasOne("Optera.Models.CategoryItem", "PriceNote")
                        .WithMany()
                        .HasForeignKey("PriceNoteId");

                    b.HasOne("Optera.Models.CategoryItem", "ValidityPeriod")
                        .WithMany()
                        .HasForeignKey("ValidityPeriodId");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("InChargePersonPosition");

                    b.Navigation("PaymentTerm");

                    b.Navigation("PriceNote");

                    b.Navigation("ValidityPeriod");
                });

            modelBuilder.Entity("Optera.Models.Region", b =>
                {
                    b.HasOne("Optera.Models.City", "City")
                        .WithMany("Regions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Optera.Models.WorkflowScenario", b =>
                {
                    b.HasOne("Optera.Models.Role", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optera.Models.Workflow", "Wokflow")
                        .WithMany("WorkflowScenarios")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Wokflow");
                });

            modelBuilder.Entity("Optera.Models.Authorization", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Optera.Models.Category", b =>
                {
                    b.Navigation("CategoryItems");
                });

            modelBuilder.Entity("Optera.Models.City", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Optera.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Optera.Models.Customer", b =>
                {
                    b.Navigation("CustomerContactPersons");

                    b.Navigation("CustomerIdentifications");
                });

            modelBuilder.Entity("Optera.Models.DataTable", b =>
                {
                    b.Navigation("DataTableColumns");
                });

            modelBuilder.Entity("Optera.Models.Employee", b =>
                {
                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("Optera.Models.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Optera.Models.Workflow", b =>
                {
                    b.Navigation("WorkflowScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
