<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Optera.Shared.Messaging</PackageId>
    <Version>1.9.1</Version>
    <Authors>Optera</Authors>
    <Company>Optera</Company>
    <Description>Optera shared messaging contracts for Optera microservices.</Description>
    <RepositoryUrl>https://github.com/your-repo-url</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
	
  <Target Name="CopyNugetToLocalFeed" AfterTargets="Pack">
    <PropertyGroup>
        <LocalFeed>..\..\Optera\NuGet</LocalFeed>
    </PropertyGroup>
    <MakeDir Directories="$(LocalFeed)" Condition="!Exists('$(LocalFeed)')" />
    <ItemGroup>
        <NuPkgFiles Include="$(PackageOutputPath)Optera.Shared.Messaging.*.nupkg" />
    </ItemGroup>
    <Copy SourceFiles="@(NuPkgFiles)" DestinationFolder="$(LocalFeed)" SkipUnchangedFiles="true" Condition="Exists('%(NuPkgFiles.Identity)')" />
  </Target>

</Project>
